/**
 * Codex CLI adapter (config surface verified against codex-cli 0.146.0 on
 * 2026-08-15). Codex enforces MORE of the never-list than a coarse sandbox:
 *
 * - Credential reads → a permission profile with OS-enforced filesystem `deny`
 *   entries (Seatbelt/Landlock). This is seamless (no trust step) and is
 *   verified to block reads of denied paths/globs. Arguably stronger than a hook.
 * - Fetched-code execution → the same self-contained shell hook the Claude Code
 *   adapter uses, wired into Codex's PreToolUse (identical payload + exit-2-block
 *   protocol). HONEST CAVEAT: non-managed Codex hooks do not fire until the user
 *   trusts them once via `/hooks` in the Codex TUI — so herkos installs it and
 *   tells the user that one step is required to activate fetched-code blocking.
 *
 * Requires Codex >= 0.146 (the permission-profile system). This is a fast-moving
 * surface — execpolicy/permissions churn is expected; re-verify per release.
 */
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawnSync } from "node:child_process";
import { collectCodexDeny, loadEffectivePolicy, compile } from "../policy.js";
import type { CompiledPolicy } from "../policy.js";
import { WireRefusalError } from "./types.js";
import type {
  HarnessAdapter,
  DetectResult,
  WireResult,
  VerifyResult,
  RuleCoverage,
  LayerKind,
  ProbeContext,
  ProbeCommand,
} from "./types.js";
import {
  commandRuns,
  withoutOwned,
  generateHook,
  herkosDir,
  hookPath,
  readInstalledStamp,
  stampOf,
} from "./claude-code.js";

const PROFILE = "herkos";
const BEGIN = "# >>> herkos managed (do not edit between markers) >>>";
const END = "# <<< herkos managed <<<";
const MIN_MAJOR = 0;
const MIN_MINOR = 146;

function codexHome(): string {
  return process.env.CODEX_HOME ?? path.join(os.homedir(), ".codex");
}
const configPath = (): string => path.join(codexHome(), "config.toml");
const hooksJsonPath = (): string => path.join(codexHome(), "hooks.json");
const rulesDir = (): string => path.join(codexHome(), "rules");
export const codexRulesPath = (): string =>
  path.join(rulesDir(), "herkos.rules");
const codexOwnedPath = (): string => path.join(herkosDir(), "codex-owned.json");

/** The Codex binary; overridable for unusual installs and for tests. */
function codexBin(): string {
  return process.env.HERKOS_CODEX_BIN ?? "codex";
}

interface CodexOwned {
  /** herkos created the rules directory — remove it once it is empty. */
  createdRulesDir: boolean;
  /** Why Codex refused the generated prefix rules at the last `init`, if it did. */
  prefixRulesRejected?: string;
}

function readCodexOwned(): CodexOwned {
  try {
    const o = JSON.parse(
      fs.readFileSync(codexOwnedPath(), "utf8"),
    ) as Partial<CodexOwned>;
    return {
      createdRulesDir: o.createdRulesDir === true,
      ...(typeof o.prefixRulesRejected === "string"
        ? { prefixRulesRejected: o.prefixRulesRejected }
        : {}),
    };
  } catch {
    return { createdRulesDir: false };
  }
}

// A JSON string literal is a valid Starlark string literal, including escaped
// quotes and backslashes (verified with codex execpolicy check, codex-cli 0.154.0).
const star = (x: string): string => JSON.stringify(x);
const starList = (xs: string[]): string => `[${xs.map(star).join(", ")}]`;

/**
 * The policy's prefix-shaped command rules as Codex execpolicy rules
 * (`prefix_rule(... decision = "forbidden")`). Codex loads these at startup with
 * no `/hooks` trust step, so a rule that is genuinely a prefix is live from the
 * first session — unlike the hook, which does nothing until the user trusts it
 * once. `null` when the policy has no prefix rules.
 *
 * Each rule carries its own prefix as a `match` example: Codex refuses to load
 * a file whose examples do not match, so the example doubles as a load-time
 * self-check of the pattern.
 *
 * Measured limits of the offline checker on codex-cli 0.154.0: a program called
 * by full path matches only when executables are resolved, and a command inside
 * `bash -lc "…"` is not split. The hook keeps covering both.
 */
export function codexRulesFile(policy: CompiledPolicy): string | null {
  const blocks: string[] = [];
  for (const r of policy.rules) {
    for (const prefix of r.commandPrefixes) {
      blocks.push(
        [
          "prefix_rule(",
          `    pattern = ${starList(prefix)},`,
          `    decision = "forbidden",`,
          `    justification = ${star(`herkos rule ${r.id} — ${r.description}. On the never-list; to adjust, narrow or disable the rule in ${policy.userPolicyPath}.`)},`,
          `    match = [${starList(prefix)}],`,
          ")",
        ].join("\n"),
      );
    }
  }
  if (blocks.length === 0) return null;
  return [
    "# Generated by herkos — do not edit; edit your policy and re-run 'herkos init'.",
    "# The never-list's prefix-shaped command rules as Codex execpolicy rules: loaded",
    "# at startup with no /hooks trust step. 'herkos uninstall' removes this file.",
    `# herkos-stamp: ${stampOf(policy)}`,
    "",
    blocks.join("\n\n"),
    "",
  ].join("\n");
}

/**
 * Ask Codex itself whether it accepts the generated rules BEFORE they go where
 * every new session loads them. A rules file Codex cannot parse is an error at
 * startup, and a config Codex refuses has already cost a live install minutes of
 * sessions that would not start — so a refusal means nothing is installed.
 */
function checkRulesWithCodex(
  file: string,
  sample: string[],
): { ok: boolean; validated: boolean; detail: string } {
  const r = spawnSync(
    codexBin(),
    ["execpolicy", "check", "--rules", file, ...sample],
    { encoding: "utf8", timeout: 20_000 },
  );
  if (r.error) {
    const code = (r.error as NodeJS.ErrnoException).code ?? r.error.message;
    return {
      ok: true,
      validated: false,
      detail: `not validated — ${codexBin()} could not run (${code})`,
    };
  }
  const lines = `${r.stdout ?? ""}\n${r.stderr ?? ""}`
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l !== "");
  for (const l of lines) {
    if (!l.startsWith("{")) continue;
    try {
      const j = JSON.parse(l) as { decision?: string };
      if (r.status === 0 && j.decision === "forbidden") {
        return {
          ok: true,
          validated: true,
          detail: "accepted by codex execpolicy check",
        };
      }
    } catch {
      // not the verdict line
    }
  }
  const errors = lines.filter((l) => /error/i.test(l)).slice(0, 2);
  return {
    ok: false,
    validated: true,
    detail:
      errors.join(" — ") ||
      `codex execpolicy check exited ${r.status ?? "?"} without a forbidden verdict`,
  };
}

function parseVersion(
  out: string,
): { major: number; minor: number; raw: string } | null {
  const m = out.match(/(\d+)\.(\d+)\.(\d+)/);
  if (!m) return null;
  return { major: Number(m[1]), minor: Number(m[2]), raw: m[0] };
}

/**
 * The one ROOT-level key herkos needs. TOML scopes a bare key to the table
 * header above it, so this line must sit before the first `[table]` in the
 * file — appended after the user's tables it silently lands inside the last
 * one, the profile is defined but never selected, and Codex refuses the
 * config ("defines [permissions] profiles but does not set
 * default_permissions"). Verified on codex-cli 0.154.0, 2026-09-11.
 */
const ROOT_MARK =
  "# >>> herkos managed root key (see the herkos block at the end) <<<";
const ROOT_LINE = `default_permissions = "${PROFILE}" ${ROOT_MARK}`;
const ROOT_RE = new RegExp(
  `^.*${ROOT_MARK.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\n?`,
  "m",
);

function buildManagedBlock(): { block: string; hasDeny: boolean } {
  const { paths, globs } = collectCodexDeny(loadEffectivePolicy());
  const lines = [
    BEGIN,
    "# herkos never-list for Codex — credential reads denied (OS-enforced via the",
    "# permission profile). Fetched-code blocking is delivered by the herkos hook",
    "# (see hooks.json); run /hooks in Codex once to trust it. 'herkos uninstall' removes this.",
    `# The selecting key, default_permissions = "${PROFILE}", is a ROOT key and lives above the first table.`,
    `[permissions.${PROFILE}]`,
    `description = "herkos never-list: credential reads denied"`,
    `extends = ":workspace"`,
    `[permissions.${PROFILE}.filesystem]`,
    ...paths.map((p) => `"${p}" = "deny"`),
    `[permissions.${PROFILE}.filesystem.":workspace_roots"]`,
    ...globs.map((g) => `"${g}" = "deny"`),
    END,
  ];
  return { block: lines.join("\n"), hasDeny: paths.length + globs.length > 0 };
}

const escapeRe = (s: string): string =>
  s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * Every managed block in the file, GLOBAL. The markers carry parentheses, so
 * they must be escaped before they become a regex: the unescaped form never
 * matched the real marker line, the block was never found again, and each
 * `init` appended one more copy until Codex refused the file ("duplicate
 * key"). Found on a live install 2026-09-11; idempotency is the adapter
 * contract (types.ts), so the block is stripped everywhere and written once.
 */
const BLOCK_RE = new RegExp(
  `\\n?${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}\\n?`,
  "gm",
);

/** A table header herkos owns: `[permissions.herkos]` or one of its subtables. */
// Matched in the spelling herkos writes. Other tools find their own sections by
// their headings the same way and leave the rest of the file alone; herkos does
// not rewrite exotic spellings of this one either, but the duplicate check
// below refuses a repeat in any spelling it can decode, so a spelling cleanup
// cannot recognize still stops the wiring instead of doubling the table.
const OWN_TABLE_RE = new RegExp(`^\\s*\\[permissions\\.${PROFILE}(\\]|\\.)`);

/**
 * Whether each line of a TOML document begins OUTSIDE a triple-quoted string.
 * A `[permissions.herkos]` written inside `developer_instructions = """…"""`
 * is an example in a string, not a table header: read as structure, cleanup
 * deleted the text after it — closing quotes included — and a valid config
 * came back as an unterminated string Codex cannot load.
 * The scan alternates open/close from the left as a parser would: outside a
 * string the first `"""`/`'''` opens one, inside it only the SAME delimiter
 * closes it (the other is content). Escapes are not tracked — no line herkos
 * writes carries one, and a hand-written `\"""` is out of scope.
 */
function structuralLineMap(lines: string[]): boolean[] {
  const structural: boolean[] = [];
  let open: string | null = null;
  for (const line of lines) {
    structural.push(open === null);
    let rest = line;
    while (rest !== "") {
      if (open === null) {
        const a = rest.indexOf('"""');
        const b = rest.indexOf("'''");
        const at = a === -1 ? b : b === -1 ? a : Math.min(a, b);
        if (at === -1) break;
        open = rest.slice(at, at + 3);
        rest = rest.slice(at + 3);
      } else {
        const at = rest.indexOf(open);
        if (at === -1) break;
        rest = rest.slice(at + 3);
        open = null;
      }
    }
  }
  return structural;
}

/**
 * Every managed block, and every herkos table left without its opening
 * marker. A tool that rewrites config.toml can drop comments and move tables
 * (seen on a live install: the opening marker was gone and the block sat
 * between other tables), and a marker-only search then appended a second
 * [permissions.herkos] that Codex refused as a duplicate key. An orphaned
 * table runs from its header to the next table that is not ours, or a stray
 * closing marker, which goes with it — never to a blank line: TOML binds the
 * keys after one to the table all the same, so a blank-line terminator
 * dropped the heading and re-homed its keys on the table above, leaving
 * duplicated `extends` keys in a config Codex refuses.
 */
function stripBlocks(content: string): string {
  const lines = content.replace(BLOCK_RE, "\n").split("\n");
  const structural = structuralLineMap(lines);
  const kept: string[] = [];
  let inOwn = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    // A line inside a triple-quoted string is the user's content, not
    // structure: example tables in it ride through untouched. herkos tables
    // hold no multiline strings, so a string opened inside one is dropped
    // with it — content lines included.
    if (!structural[i]) {
      if (!inOwn) kept.push(line);
      continue;
    }
    if (OWN_TABLE_RE.test(line)) {
      inOwn = true;
      continue;
    }
    if (line.trim() === END) {
      inOwn = false;
      continue;
    }
    // The next table that is not ours ends the orphan; what follows is the
    // user's.
    if (inOwn && /^\s*\[/.test(line)) inOwn = false;
    if (!inOwn) kept.push(line);
  }
  return kept.join("\n");
}

/**
 * The table a `[…]` line DEFINES, as decoded key parts: `[permissions.herkos]`,
 * `[permissions."herkos"]` and `[ permissions . herkos ]` are the same table.
 * Quoted parts decode (basic strings unescape, literal strings stay verbatim,
 * so quoted spacing survives); a line herkos cannot decode — no closing
 * bracket, an unterminated quote, junk after the bracket — returns null and
 * is never treated as ours.
 */
function tablePathOf(line: string): string[] | null {
  const s = line.trim();
  if (!s.startsWith("[")) return null;
  const arrayTable = s.startsWith("[[");
  let i = arrayTable ? 2 : 1;
  const parts: string[] = [];
  let cur = "";
  let partQuoted = false;
  let quote: string | null = null;
  let closedAt = -1;
  for (; i < s.length; i++) {
    const ch = s[i]!;
    if (quote) {
      if (quote === '"' && ch === "\\" && i + 1 < s.length) {
        cur += s[i + 1]!;
        i++;
        continue;
      }
      if (ch === quote) quote = null;
      else cur += ch;
      continue;
    }
    if (ch === '"' || ch === "'") {
      quote = ch;
      partQuoted = true;
      continue;
    }
    if (ch === "]") {
      if (arrayTable && s[i + 1] !== "]") return null;
      if (arrayTable) i++;
      closedAt = i + 1;
      break;
    }
    if (ch === ".") {
      parts.push(partQuoted ? cur : cur.trim());
      cur = "";
      partQuoted = false;
      continue;
    }
    if (ch === "#") return null; // a comment before the bracket closed
    cur += ch;
  }
  if (closedAt === -1 || quote !== null) return null;
  parts.push(partQuoted ? cur : cur.trim());
  if (parts.some((p) => p === "")) return null;
  // After the bracket only whitespace or a comment may follow.
  const tail = s.slice(closedAt).trim();
  if (tail !== "" && !tail.startsWith("#")) return null;
  return parts;
}

/**
 * Every heading that resolves to herkos's table or a subtable of it, counted
 * by the table it DEFINES rather than the bytes it spells. This shared the
 * heading matcher with cleanup once, so a spelling cleanup cannot recognize —
 * `[permissions."herkos"]` — slipped past the guard too and wiring appended a
 * second copy of the same table. Such a spelling is still
 * never rewritten; wiring refuses and names it.
 */
function duplicateOwnTables(content: string): string[] {
  const lines = content.split("\n");
  const structural = structuralLineMap(lines);
  const seen = new Map<string, number>();
  const spelling = new Map<string, string>();
  for (let i = 0; i < lines.length; i++) {
    if (!structural[i]) continue;
    const parts = tablePathOf(lines[i]!);
    if (!parts || parts[0] !== "permissions" || parts[1] !== PROFILE) continue;
    const key = JSON.stringify(parts);
    seen.set(key, (seen.get(key) ?? 0) + 1);
    if (!spelling.has(key)) spelling.set(key, lines[i]!.trim());
  }
  return [...seen].filter(([, n]) => n > 1).map(([k]) => spelling.get(k)!);
}

/**
 * Append the block at the end, always after a blank line: that is where a
 * careful tool stops when it deletes the table above. One that deletes up to
 * the next header can still take the opening marker; stripBlocks then finds
 * the tables by their heading.
 */
function upsertBlock(content: string, block: string): string {
  const c = stripBlocks(content).replace(/\n+$/, "");
  return `${c}${c ? "\n\n" : ""}${block}\n`;
}

/**
 * Drop herkos's root selector, marked or bare. A tool that strips comments
 * takes the marker off `default_permissions = "herkos" # …`, and the bare
 * line then survived uninstall while the profile table went with it — a
 * selector naming a profile that no longer exists, which Codex refuses to
 * load. Only the root-section spelling goes: the same key
 * deeper in the file belongs to a table and is somebody else's.
 */
function removeRootLine(content: string): string {
  const lines = content.replace(ROOT_RE, "").split("\n");
  const structural = structuralLineMap(lines);
  const end = lines.findIndex(
    (l, i) => structural[i] && (/^\s*\[/.test(l) || l.startsWith(BEGIN)),
  );
  const root = end === -1 ? lines : lines.slice(0, end);
  const bare = /^\s*default_permissions\s*=\s*"herkos"\s*(?:#.*)?$/;
  return [
    ...root.filter((l) => !bare.test(l)),
    ...(end === -1 ? [] : lines.slice(end)),
  ].join("\n");
}

/**
 * Put the root line in the root section: before the first table header, or
 * before our own managed block if that comes first, else at the end. Any
 * previous herkos root line is removed first, so the call is idempotent.
 */
function upsertRootLine(content: string): string {
  const c = removeRootLine(content);
  const lines = c.split("\n");
  let at = lines.findIndex((l) => /^\s*\[/.test(l) || l.startsWith(BEGIN));
  if (at === -1) at = lines.length;
  const before = lines.slice(0, at);
  const after = lines.slice(at);
  // Keep the file tidy: a blank line between the user's root keys and ours.
  if (before.length && before[before.length - 1]?.trim() !== "")
    before.push("");
  return [...before, ROOT_LINE, ...after].join("\n");
}

/** Is the herkos root line present in the ROOT section (above every table)? */
function rootLineActive(content: string): boolean {
  const idx = content.indexOf(ROOT_LINE);
  if (idx === -1) return false;
  const head = content.slice(0, idx);
  return !/^\s*\[/m.test(head);
}

/**
 * The value of the FIRST `default_permissions` in the root section — marked,
 * bare (a comment-stripper's doing), or the user's own. Codex binds the key
 * to whichever table is current, so only a root-section occurrence selects a
 * profile; one deeper in the file is an ordinary key herkos does not touch.
 * Null when the root section sets none.
 */
function rootSelectorValue(content: string): string | null {
  const lines = content.split("\n");
  const structural = structuralLineMap(lines);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (structural[i] && (/^\s*\[/.test(line) || line.startsWith(BEGIN)))
      return null;
    if (!structural[i]) continue;
    const m = line.match(/^\s*default_permissions\s*=\s*"([^"]*)"/);
    if (m) return m[1]!;
  }
  return null;
}

/**
 * Read Codex's hooks.json and refuse a shape herkos cannot merge into — the
 * same contract as the Claude Code adapter's settings gate. A string `hooks`
 * or a non-array `PreToolUse` would silently swallow the registration (or
 * throw) mid-wire; wire() calls this BEFORE anything is written, so a refused
 * init is a clean no-op.
 */
function readHooksDocForWire(): {
  doc: { hooks?: Record<string, unknown[]> };
  existed: boolean;
} {
  const p = hooksJsonPath();
  if (!fs.existsSync(p)) return { doc: {}, existed: false };
  let parsed: unknown;
  try {
    parsed = JSON.parse(fs.readFileSync(p, "utf8"));
  } catch (e) {
    throw new WireRefusalError(
      `${p} is not valid JSON (${String((e as Error).message)}) — fix or remove it, then re-run 'herkos init'`,
    );
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new WireRefusalError(
      `${p} holds ${Array.isArray(parsed) ? "an array" : parsed === null ? "null" : `a ${typeof parsed}`}, not a JSON object — fix or remove it, then re-run 'herkos init'`,
    );
  }
  const doc = parsed as { hooks?: Record<string, unknown[]> };
  const rawHooks: unknown = doc.hooks;
  if (
    rawHooks !== undefined &&
    (typeof rawHooks !== "object" ||
      rawHooks === null ||
      Array.isArray(rawHooks))
  ) {
    throw new WireRefusalError(
      `your hooks.json has 'hooks' as ${Array.isArray(rawHooks) ? "an array" : rawHooks === null ? "null" : `a ${typeof rawHooks}`} — herkos cannot merge into that; fix or remove it, then re-run 'herkos init'`,
    );
  }
  const rawPre: unknown = (rawHooks as Record<string, unknown> | undefined)?.[
    "PreToolUse"
  ];
  if (rawPre !== undefined && !Array.isArray(rawPre)) {
    throw new WireRefusalError(
      `your hooks.json has 'hooks.PreToolUse' as ${rawPre === null ? "null" : `a ${typeof rawPre}`} — herkos cannot merge into that; fix or remove it, then re-run 'herkos init'`,
    );
  }
  return { doc, existed: true };
}

// Wire the shared hook into Codex's hooks.json (root wrapper key "hooks").
function wireHook(doc: { hooks?: Record<string, unknown[]> }): void {
  const p = hooksJsonPath();
  if (fs.existsSync(p)) {
    const bak = `${p}.herkos-bak`;
    if (!fs.existsSync(bak)) fs.copyFileSync(p, bak);
  }
  const hooks = doc.hooks ?? {};
  // The harness name reaches the blocked-call log; the hook path stays the
  // ownership marker, so an entry written before the argument existed is still ours.
  const cmd = `sh "${hookPath()}" --harness codex`;
  const pre = withoutOwned((hooks["PreToolUse"] as unknown[]) ?? [], (c) =>
    commandRuns(c, hookPath()),
  );
  pre.push({ matcher: "^Bash$", hooks: [{ type: "command", command: cmd }] });
  hooks["PreToolUse"] = pre;
  doc.hooks = hooks;
  fs.mkdirSync(codexHome(), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(doc, null, 2) + "\n");
}

/**
 * Does hooks.json content wire the herkos hook? The file is parsed and each
 * command checked with commandRuns; JSON that will not parse says "not
 * wired". Matching on the raw text instead claimed a path merely MENTIONED
 * in it — a wrapper that cats the script read as a wiring, and status
 * reported enforcement that was not there.
 */
export function hookWiredInHooksJson(text: string): boolean {
  let doc: unknown;
  try {
    doc = JSON.parse(text);
  } catch {
    return false;
  }
  const hooks = (doc as { hooks?: unknown } | null)?.hooks;
  if (!hooks || typeof hooks !== "object") return false;
  return Object.values(hooks as Record<string, unknown>).some((entries) => {
    if (!Array.isArray(entries)) return false;
    return entries.some((e) => {
      const inner = (e as { hooks?: unknown } | null)?.hooks;
      if (!Array.isArray(inner)) return false;
      return inner.some((h) =>
        commandRuns(
          String((h as { command?: unknown } | null)?.command ?? ""),
          hookPath(),
        ),
      );
    });
  });
}

export const codexAdapter: HarnessAdapter = {
  id: "codex",
  name: "Codex CLI",
  hookScope: "shell-commands",

  detect(): DetectResult {
    const r = spawnSync(codexBin(), ["--version"], {
      encoding: "utf8",
      timeout: 15_000,
    });
    if (r.status !== 0 || r.error)
      return { installed: false, detail: "codex not found on PATH" };
    const raw = (r.stdout ?? "").trim().split("\n")[0] ?? "";
    const v = parseVersion(raw);
    if (
      v &&
      (v.major < MIN_MAJOR || (v.major === MIN_MAJOR && v.minor < MIN_MINOR))
    ) {
      return {
        installed: true,
        version: v.raw,
        configDir: codexHome(),
        detail: `${v.raw} — below the ${MIN_MAJOR}.${MIN_MINOR} minimum for the permission-profile system; upgrade Codex for credential enforcement`,
      };
    }
    return {
      installed: true,
      version: v?.raw ?? raw,
      configDir: codexHome(),
      detail: `${v?.raw ?? raw} · config at ${configPath()}`,
    };
  },

  // The compiled policy is used for the shared hook; the filesystem-deny profile
  // is built from the effective policy's codexDeny targets.
  wire(policy: CompiledPolicy): WireResult {
    const changed: string[] = [];
    const p = configPath();
    fs.mkdirSync(codexHome(), { recursive: true });

    // 0. Refuse a hooks.json herkos cannot merge into BEFORE anything is
    //    written, so a refused init is a clean no-op (no config.toml rewrite,
    //    no hook file, no half-applied install).
    const hooksDoc = readHooksDocForWire();

    // 1. credential-read → permission-profile deny (config.toml managed block)
    let content = "";
    if (fs.existsSync(p)) {
      content = fs.readFileSync(p, "utf8");
      const bak = `${p}.herkos-bak`;
      if (!fs.existsSync(bak)) {
        fs.copyFileSync(p, bak);
        changed.push(bak);
      }
    }
    // Refuse to clobber a user's own default_permissions set OUTSIDE our block.
    const outside = stripBlocks(removeRootLine(content));
    const conflict = /^\s*default_permissions\s*=/m.test(outside);
    const { block } = buildManagedBlock();
    // Tables go at the end; the selecting root key goes above the first table.
    let next = upsertBlock(content, block);
    if (!conflict) next = upsertRootLine(next);
    // Codex refuses a file with a repeated table, and then no Codex session
    // starts. Never write one: refuse loudly and leave the file as it was.
    const dupes = duplicateOwnTables(next);
    if (dupes.length > 0) {
      throw new WireRefusalError(
        `${p} would define ${dupes.join(", ")} more than once — the same table in a different spelling counts — which Codex refuses; nothing was written. Remove the extra herkos table(s) by hand, then re-run 'herkos init'`,
      );
    }
    fs.writeFileSync(p, next);
    changed.push(p);

    // 2. fetched-exec → shared hook, wired into hooks.json (needs /hooks trust)
    fs.mkdirSync(path.dirname(hookPath()), { recursive: true });
    fs.writeFileSync(hookPath(), generateHook(policy), { mode: 0o755 });
    wireHook(hooksDoc.doc);
    changed.push(hookPath(), hooksJsonPath());

    // 3. prefix-shaped command rules → execpolicy forbidden rules: live at
    //    startup, no trust step. Codex checks them before they are installed.
    const owned = readCodexOwned();
    const nextOwned: CodexOwned = { createdRulesDir: owned.createdRulesDir };
    const rulesText = codexRulesFile(policy);
    const prefixCount = policy.rules.reduce(
      (n, r) => n + r.commandPrefixes.length,
      0,
    );
    let prefixNote = "";
    if (rulesText === null) {
      if (fs.existsSync(codexRulesPath())) {
        fs.rmSync(codexRulesPath());
        changed.push(codexRulesPath());
      }
    } else {
      const staged = path.join(herkosDir(), "herkos.rules.staged");
      fs.writeFileSync(staged, rulesText);
      const sample = policy.rules.flatMap((r) => r.commandPrefixes)[0] ?? [];
      const verdict = checkRulesWithCodex(staged, sample);
      if (verdict.ok) {
        if (!fs.existsSync(rulesDir())) {
          fs.mkdirSync(rulesDir(), { recursive: true });
          nextOwned.createdRulesDir = true;
        }
        fs.copyFileSync(staged, codexRulesPath());
        changed.push(codexRulesPath());
        prefixNote = ` ${prefixCount} command prefix rule(s) live via execpolicy now, no trust step (${verdict.detail}).`;
      } else {
        if (fs.existsSync(codexRulesPath())) {
          fs.rmSync(codexRulesPath());
          changed.push(codexRulesPath());
        }
        nextOwned.prefixRulesRejected = verdict.detail;
        prefixNote = ` Codex REFUSED the generated prefix rules (${verdict.detail}) — none were installed; those rules ride the hook only.`;
      }
      fs.rmSync(staged, { force: true });
    }
    fs.writeFileSync(
      codexOwnedPath(),
      JSON.stringify(nextOwned, null, 2) + "\n",
    );

    const trustNote =
      "Run '/hooks' in Codex ONCE to trust the herkos hook — until then, rules only the hook carries (such as fetched code piped to a shell) are inactive; credential denies and prefix rules are already live.";
    const conflictNote = conflict
      ? " NOTE: you already set default_permissions outside herkos's block — point it at \"herkos\" or merge, or the credential profile won't be the active one."
      : "";
    return {
      changed,
      detail: `credential reads denied via the '${PROFILE}' permission profile (OS-enforced).${prefixNote} ${trustNote}${conflictNote}`,
    };
  },

  unwire(): WireResult {
    const changed: string[] = [];
    const p = configPath();
    if (fs.existsSync(p)) {
      const c = fs.readFileSync(p, "utf8");
      if (
        c.includes(BEGIN) ||
        ROOT_RE.test(c) ||
        c.split("\n").some((l) => OWN_TABLE_RE.test(l)) ||
        rootSelectorValue(c) === PROFILE
      ) {
        fs.writeFileSync(p, removeRootLine(stripBlocks(c)));
        changed.push(p);
      }
    }
    const hp = hooksJsonPath();
    let hooksJsonUnreadable = false;
    if (fs.existsSync(hp)) {
      let doc: { hooks?: Record<string, unknown[]> } = {};
      try {
        doc = JSON.parse(fs.readFileSync(hp, "utf8")) as typeof doc;
      } catch {
        // Leave the file alone, but say so: an unreadable hooks.json is
        // exactly where our registration can survive an uninstall that
        // reported success (degrade loudly, never fail silently).
        doc = {};
        hooksJsonUnreadable = true;
      }
      const hooks = doc.hooks ?? {};
      const pre = hooks["PreToolUse"];
      if (Array.isArray(pre)) {
        const kept = withoutOwned(pre, (c) => commandRuns(c, hookPath()));
        if (JSON.stringify(kept) !== JSON.stringify(pre)) {
          // Leave no empty skeleton behind (the Claude adapter's rule): an
          // emptied event key goes, an emptied hooks wrapper goes, and a file
          // that held nothing but our registration — wire creates it when
          // absent — is removed, restoring the pre-herkos state exactly.
          if (kept.length === 0) delete hooks["PreToolUse"];
          else hooks["PreToolUse"] = kept;
          if (Object.keys(hooks).length === 0) delete doc.hooks;
          if (Object.keys(doc).length === 0) {
            fs.rmSync(hp);
          } else {
            fs.writeFileSync(hp, JSON.stringify(doc, null, 2) + "\n");
          }
          changed.push(hp);
        }
      }
    }
    if (fs.existsSync(codexRulesPath())) {
      fs.rmSync(codexRulesPath());
      changed.push(codexRulesPath());
    }
    const owned = readCodexOwned();
    if (
      owned.createdRulesDir &&
      fs.existsSync(rulesDir()) &&
      fs.readdirSync(rulesDir()).length === 0
    ) {
      fs.rmdirSync(rulesDir());
      changed.push(rulesDir());
    }
    fs.rmSync(codexOwnedPath(), { force: true });
    return {
      changed,
      detail:
        (changed.length ? "herkos Codex wiring removed" : "nothing to remove") +
        (hooksJsonUnreadable
          ? ` — WARNING: ${hp} could not be parsed, so herkos's PreToolUse registration may still be in it; fix or delete that file by hand and re-run 'herkos uninstall'`
          : ""),
    };
  },

  verify(): VerifyResult {
    const p = configPath();
    if (!fs.existsSync(p) || !fs.readFileSync(p, "utf8").includes(BEGIN)) {
      return {
        ok: false,
        detail: "credential-deny profile not present — run 'herkos init'",
      };
    }
    const cfg = fs.readFileSync(p, "utf8");
    if (!rootLineActive(cfg) && rootSelectorValue(cfg) !== PROFILE) {
      return {
        ok: false,
        detail:
          "credential-deny profile present but NOT selected — default_permissions is missing from the root section, so the OS deny is inactive; run 'herkos init'",
      };
    }
    const hookWired =
      fs.existsSync(hooksJsonPath()) &&
      hookWiredInHooksJson(fs.readFileSync(hooksJsonPath(), "utf8"));
    // Prefix rules: live, refused by Codex at the last init, or missing/stale.
    const current = compile(loadEffectivePolicy());
    let prefixDetail = "";
    if (current.rules.some((r) => r.commandPrefixes.length > 0)) {
      const owned = readCodexOwned();
      if (owned.prefixRulesRejected) {
        prefixDetail = `; prefix rules NOT live — Codex refused them at the last init (${owned.prefixRulesRejected}), so they ride the hook only`;
      } else if (!fs.existsSync(codexRulesPath())) {
        return {
          ok: false,
          state: "stale",
          detail: `credential-deny profile present, but the execpolicy prefix rules are missing from ${codexRulesPath()} — run 'herkos init'`,
        };
      } else if (readInstalledStamp(codexRulesPath()) !== stampOf(current)) {
        return {
          ok: false,
          state: "stale",
          detail: `the execpolicy prefix rules at ${codexRulesPath()} carry an older policy — run 'herkos init'`,
        };
      } else {
        prefixDetail = "; prefix rules live via execpolicy (no trust step)";
      }
    }
    return {
      ok: true,
      state: "ok",
      detail: `credential-deny profile present (OS-enforced)${prefixDetail}${hookWired ? "; hook wired for shell commands (needs '/hooks' trust in Codex to be active)" : "; hook NOT wired"}`,
    };
  },

  liveProbeCommand(ctx: ProbeContext): ProbeCommand {
    // codex exec is the single-turn headless mode. It runs in the decoy's
    // directory against the real config and profile. Codex exec has no budget
    // flag, so the wall-clock timeout is the whole ceiling here; the report
    // says so. --skip-git-repo-check because the throwaway dir is not a repo.
    return {
      bin: codexBin(),
      args: [
        "exec",
        "--skip-git-repo-check",
        "--cd",
        ctx.workingDir,
        ctx.prompt,
      ],
      env: { ...process.env },
      ceilingNote:
        "codex exec has no budget flag — the wall-clock timeout is the ceiling",
    };
  },

  coverage(policy: CompiledPolicy): RuleCoverage[] {
    const cfg = fs.existsSync(configPath())
      ? fs.readFileSync(configPath(), "utf8")
      : "";
    const profileLive =
      cfg.includes(BEGIN) &&
      (rootLineActive(cfg) || rootSelectorValue(cfg) === PROFILE);
    const hookLive =
      fs.existsSync(hookPath()) &&
      fs.existsSync(hooksJsonPath()) &&
      hookWiredInHooksJson(fs.readFileSync(hooksJsonPath(), "utf8"));
    const prefixLive =
      fs.existsSync(codexRulesPath()) && !readCodexOwned().prefixRulesRejected;
    const effective = loadEffectivePolicy();
    return policy.rules.map((r) => {
      const layers: string[] = [];
      const kinds: LayerKind[] = [];
      if (r.disposition === "open") {
        return {
          rule: r.id,
          layers: hookLive
            ? ["hook notice (advisory, after '/hooks' trust)"]
            : [],
          kinds: [],
        };
      }
      const source = effective.rules.find((x) => x.id === r.id);
      if (profileLive && (source?.codexDeny ?? []).length > 0) {
        layers.push("permission profile (OS deny)");
        kinds.push("os-sandbox");
      }
      if (prefixLive && r.commandPrefixes.length > 0) {
        layers.push("execpolicy forbidden rules (no trust step)");
        kinds.push("prefix-rule");
      }
      if (hookLive && (r.pathRegex !== "" || r.commandRegexes.length > 0)) {
        layers.push("hook on shell commands (after '/hooks' trust)");
        kinds.push("hook");
      }
      return { rule: r.id, layers, kinds };
    });
  },
};

/** For live validation: the config block herkos would write (used by the canary test). */
export function previewManagedBlock(): string {
  void compile(loadEffectivePolicy());
  return buildManagedBlock().block;
}
