/**
 * The installed package version, read at run time from package.json.
 *
 * It is baked into every generated hook as part of its stamp, so `status` and
 * the session-start line can tell "this hook was generated by an older herkos
 * than the one now installed" from "the hook is current". Never throws: an
 * unreadable package.json degrades to "unknown" rather than failing a command.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

function readVersion(): string {
  let dir = path.dirname(fileURLToPath(import.meta.url));
  // src/version.ts (tests) and dist/cli.js (installed) both sit one level under
  // the package root; walk up a few levels so neither layout needs a special case.
  for (let i = 0; i < 4; i++) {
    try {
      const pkg = JSON.parse(
        fs.readFileSync(path.join(dir, "package.json"), "utf8"),
      ) as { name?: string; version?: string };
      if (pkg.name === "herkos" && typeof pkg.version === "string") {
        return pkg.version;
      }
    } catch {
      // not this level — keep walking up
    }
    const up = path.dirname(dir);
    if (up === dir) break;
    dir = up;
  }
  return "unknown";
}

export const HERKOS_VERSION: string = readVersion();
